services:
  managerapp:
    build: 
      './1st microservice ManagerHome PAD/Manager_App/'
    ports:
      - "59150:80"

  calculator:
    build: 
      './2nd microservice CalculatorBTU/CalculatorBTU/'
    ports:
      - "59160:80"

  webscrapper:
    build: 
      './3rd microservice web scrapping/'
    ports:
      - "59170:5000"

  mongo:
    image: 
      mongo
    restart: 
      always
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
    volumes: 
      - dbdata:/data/db

  mongo-express:
    image: 
      mongo-express
    restart: 
      always
    ports:
      - 59165:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: example
      ME_CONFIG_MONGODB_URL: mongodb://root:example@mongo:27017/
      ME_CONFIG_BASICAUTH: false

volumes:
  dbdata: