name: CI/CD for ManagerApp Service

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Run docker-compose
        uses: hoverkraft-tech/compose-action@v2.0.1
        with:
          compose-file: "./docker-compose.yml"

      - name: Test connection between front and ytdlp
        run: |
          sleep 2  # Give services time to start
          docker exec managerapp-1 ping -c 3 calculator-1 || exit 1
          docker exec managerapp-1 ping -c 3 webscrapper-1 || exit 1
          docker exec managerapp-1 ping -c 3 mongo-1 || exit 1
          docker exec managerapp-1 ping -c 3 mongo-express-1 || exit 1

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push Docker image
        run: |
          docker build -t ${{ secrets.DOCKER_USERNAME }}/front:latest ./Front
          docker push ${{ secrets.DOCKER_USERNAME }}/front:latest

      - name: Cleanup
        run: |
          docker-compose down
